- name: Install and configure atlassian jira software
  hosts: all
  gather_facts: true
  tasks:
    - include_role:
        name: confluenceinstall

    - include_role:
        name: linux_certreq

    - include_role:
        name: confluence_certconfig
      when: custom_certpath is defined